# Ecrire un GitHub Action qui utilise le Dockerfile pour build une image et la pousser sur le Docker hub. Il se déclenche sur push sur la branche main

name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Je dois utiliser Docker"
